name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ libgl1-mesa-dev libglu1-mesa-dev cmake git
        # 安装X11和Wayland开发库
        sudo apt-get install -y libx11-dev libxext-dev libxrandr-dev libxinerama-dev libxi-dev
        sudo apt-get install -y libwayland-dev wayland-protocols libwayland-egl-backend-dev
        # 安装其他图形相关依赖
        sudo apt-get install -y libasound2-dev libdbus-1-dev libudev-dev libinput-dev
        
    - name: Build and install SDL3
      run: |
        git clone https://github.com/libsdl-org/SDL.git
        cd SDL
        mkdir build
        cd build
        cmake .. -DSDL_VIDEO_DRIVER_X11=ON -DSDL_VIDEO_DRIVER_WAYLAND=ON
        make
        sudo make install
        
    - name: Build project
      run: |
        g++ -o goldberg -I/usr/local/include/SDL3 -I/usr/include/GL goldberg.cpp *.cpp -lGL -lGLU -lSDL3
        
    - name: Copy shaders
      run: |
        cp fragmentshader.glsl vertexshader.glsl build/
        
    - name: Run tests
      run: ./goldberg
